### PR TITLE
Create config file and track compute resources during the subprocess call

### PR DESCRIPTION
**Pull request by adbailey4**
* made taskManager pip installable 
* generate executable script taskManager
* configure a config file in so we do not have to deal with passing in same arguments over and over
* maintain functionality of other scripts
* reorganize project directory structure
* add some basic tests

### CODE REVIEW

**Comment by rlorigro** [comment]
Mostly looks good, though a few things could be changed:

- This `Copyright (c) 2017 Andrew D Bailey IV` should be changed to something else. @tpesout and I have both contributed to this project. Not sure how this kid of thing works with multiple authors
- `All checks have failed`. Why?
- I don't entirely agree with the reorganization. Before it was clear what is an executable script and what is just a module (containing reusable code) used for scripts.
- It looks like py3helpers is still being imported, but I would prefer not to add dependencies like pysam

**Comment by ghost** [comment]
Logfile option documentation is not very helpful
Figure out how to pipe stderr correctly

**Comment by adbailey4** [comment]
* I changed py3helpers to not install pysam and the other heavy dependencies by default so we can keep it as a package.
* Updated Manual (did not include information regarding the other scripts)
* Updated version and added travis tag to show tests are passing

**Comment by rlorigro** [comment]
I have a couple minor recommendations (If these aren't your code then just let me know, I will fix them myself) :

1. Swap the order of the README. Features and examples should be first, details about how to use it should come afterwards. In other words: why would people want to know how to use it before knowing what it does?
2. Refactor `AWSNotifier.upload_to_s3()` so that the function itself handles exceptions that may arise during uploading (see [this line](https://github.com/rlorigro/TaskManager/blob/8855e17ec5be3809233f95c0ddabce6ef2f58cf7/taskManager/ResourceMonitor.py#L164)) 
3. In the taskManager executable argparser, the [comma separated list](https://github.com/rlorigro/TaskManager/blob/8855e17ec5be3809233f95c0ddabce6ef2f58cf7/bin/taskManager#L141) should be parsed using `argparser.register`, as is done with [`space_separated_list`](https://github.com/rlorigro/TaskManager/blob/8855e17ec5be3809233f95c0ddabce6ef2f58cf7/bin/taskManager#L52). This should default to `None` if left unspecified, which should remove the need for that extra if/else statement...
4. Also it seems like `select_not_none` doesn't need to exist, because argparser has a parameter called `default`, which should provide an argument whenever none is given by the user.
5. Maybe delete the duplicate parser `space_separated_arguments` (I can do this if you don't feel like it)

**Comment by rlorigro** [comment]
nice job Andrew Bailey :clap:

**Pull request merged**
