### PR TITLE
Rm py3helpers

### PR DESCRIPTION
**Pull request by adbailey4**
Removed py3helpers dependency and updated readme and travis accordingly

### CODE REVIEW

**Comment by rlorigro** [comment]
can you post an image of the plot in its current state?

**Comment by adbailey4** [comment]
log_20201029-133434-813322

**Comment by rlorigro** [comment]
the ticks on the left side of the axis need to be off

**Comment by rlorigro** [comment]
also the values are totally broken now??

**Comment by rlorigro** [comment]
there are basically 2 "axes" objects on the same plot, the one on the right has this specific tick which indicates the min/max, but the one of the left should only be the regular tick marks. It looks like the right side axis is displaying on both sides

**Pull request merged**
